### ISSUE TITLE
Navigation aid for missions

### ISSUE THREAD

**Issue by ricmzn** [jtoppins/dct#151]
Suggested by vsTerminus

An option could be added for getting a navigation aid to the objective without the need for F10 map usage, especially aimed at older aircraft with no coordinate-based navigation systems. The idea is that it would give a range and a bearing to the current mission marker, akin to GCI home plate calls, allowing navigation even in low visibility.

**Comment by jtoppins** [comment]
I do not see random TACAN stations being placed at targets without there being a reason for them being there like a JTAC and/or friendly force observer. It just doesn't make sense otherwise. So as far as DCT automatically placing an ADF/TACAN on a target I don't see that happening much in an automated way. CSAR pilot pickup would be an obvious one where it would make sense for an ADF to exist on the pilot.

Currently templates are limited to a single side only. Allowing multiple sides to exist in the same template would allow for template/campaign designers to provide nav aids if they wanted. We would have to figure out how to mark which side ultimately owns the generated asset from the template.

**Comment by ricmzn** [comment]
What about it being given as purely an UI feature (ie. outText the approximate range and bearing on request)?

**Comment by jtoppins** [comment]
Again why, what reason would a nav-aid be there?
