### ISSUE TITLE
Create a Windows installer for DCT

### ISSUE THREAD

**Issue by jtoppins** [jtoppins/dct#69]
We currently have a DCS module building but do not have a Windows installer.

## Requirements

* must be able to build the installer on a Linux platform (Ubuntu or Fedora)

## Possible Options

* [NSIS](https://nsis.sourceforge.io/Main_Page)
* [Qt Installer Framework](https://doc.qt.io/qtinstallerframework/ifw-getting-started.html) (requires license - not ideal)

**Comment by ricmzn** [comment]
The user already needs to know where their saved games folder is to install theater files, so we might as well have them drop DCT there in the process. I've instead re-structured the built zip so that all the folders are ready for a single drag-and-drop instead of having to navigate through multiple folders for an install (https://github.com/team-limakilo/dct/commit/697656410236d84f246e1406ea1682d9798f6ec1). Is this good enough, or does an installer include additional benefits? I could see the installer being useful if we eventually include game mods (ie. custom mission editor menus) that need to be carefully merged into existing game files.

**Comment by jtoppins** [comment]
I am not big on installers and it would just add a lot of code bloat for probably little benefit. Those changes seem like a reasonable middle ground. If we ever do a mission editor mode then we can revisit. Please create a PR and we can close this one out.
